blog/config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :articles, :users, :comments

  root 'articles#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  #associations
  has_many :comments
  belongs_to :author, class_name: 'User'

  #validations

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base

  #associations
  belongs_to :article
  belongs_to :author, class_name: 'User'

  #validations

end

blog/app/models/user.rb
class User < ActiveRecord::Base

  #associations
  has_many :comments
  has_many :articles, foreign_key: "author_id"
  has_secure_password


  #validations

end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  include SessionsHelper

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)

    unless @article.valid?
       flash[:error] = @article.errors.full_messages.join("<br>").html_safe
     else
       flash[:success] = "Todo added successfully"
     end
    redirect_to :action => 'index'

    # if @article.save
    #   redirect_to :action => :index
    # else
    #   render 'new'
    # end
  end

  def article_params
    params.require(:article).permit(:hed, :dek, :body).merge(author_id: current_user.id)
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end


end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  def log_out
    session[:user_id] = nil
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :action => :index
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :salt, :encrypted_password)
  end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    current_user != nil
  end
end

blog/app/views/articles/index.html.erb
<h1>All Loquor Articles</h1>

<% if flash[:error] %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= flash[:error] %></strong>
  </div>
<% end %>

<% if flash[:success] %>
 <div class="alert alert-success">
   Article Successfully Posted!!!
 </div>
<% end %>

<ul>
  <% @articles.each do |article| %>
    <li>
      <p><strong><%= link_to article.hed, article %></strong></p>
      <p><em><%= article.dek %></em></p>
    </li>
  <% end %>
</ul>

blog/app/views/articles/new.html.erb
<h1>Create A New Article</h1>
<br>
<%= form_for @article, url: {action: "create"} do |f| %>
  <%= f.label :hed %>
  <%= f.text_field :hed, placeholder: "Title your article here" %>
  <br>
  <%= f.label :dek %>
  <%= f.text_field :dek, placeholder: "Write a short description here." %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body, placeholder: "Write your article here.", size: "60x12" %>
  <%= f.submit "Post Article" %>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loquor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to 'Loquor', '/', class: "nav-link" %>
    <%= link_to 'Articles', articles_path(@articles), class: "nav-link" %>
    <%= link_to 'Users', users_path(@users), class: "nav-link" %>
  </nav>
  <hr>
  <header>
    <section id="session">
      <% if logged_in? %>
        <span>Logged in as: <%= link_to current_user.first_name, current_user, class: "session-link" %> | </span>
        <%= link_to 'LOGOUT', logout_path, method: :delete, class: "session-link" %>
      <% else %>
        <%= link_to "Login", login_path, class: "session-link" %> |
        <%= link_to 'Register', new_user_path, class: "session-link" %>
      <% end %>
    </section>
  </header>
  <hr>

<%= yield %>

</body>
</html>

blog/app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <p>Name: <%= link_to user.first_name, user %></p>
      <p>Email: <%= user.email %></p>
    </li>
  <% end %>
</ul>

blog/app/views/users/new.html.erb
<h1>Create A New User</h1>
<br>
<%= form_for(@user) do |f| %>
  <div class="fields">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, placeholder: "First Name" %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
    <br>
    <hr>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Email adddress" %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="buttons">
    <%= f.submit "Register" %>
  </div>
<% end %>